# ubuntu
FROM wuhaocn/javaapp:8

# MAINTAINER
MAINTAINER wuhaocn@126.com
VOLUME ["/tmp"]



RUN apt-get update

RUN apt-get -y install vim

RUN apt-get -y install net-tools
RUN apt -y install mongodb wget git
RUN apt -y install git gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev






