# base image
FROM wuhaocn/java-im:1

# MAINTAINER
MAINTAINER wuhaocn@126.com
VOLUME ["/tmp"]


#设置环境变量
# ADD sql/*.sql /docker-entrypoint-initdb.d/
# ADD sh/*.sh /usr/local/bin/

RUN rm -rf /docker-entrypoint-initdb.d/DrawDB.sql


# RUN chmod -R 777 /usr/local/bin
# RUN chmod -R 777 /root
# RUN echo "/usr/local/bin/run-im.sh" >> /usr/local/bin/run-server.sh



