package com.coral.kbs.tool.count;

/**
 * @author wuhao
 * @createTime 2021-05-18 11:39:00
 */
public class StrCountRefer {
    static final String str = "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "copy\n" +
            "copy\n" +
            "ping\n" +
            "set\n" +
            "set\n" +
            "get\n" +
            "getDel\n" +
            "getEx\n" +
            "exists\n" +
            "exists\n" +
            "del\n" +
            "del\n" +
            "unlink\n" +
            "unlink\n" +
            "type\n" +
            "keys\n" +
            "randomKey\n" +
            "rename\n" +
            "renamenx\n" +
            "expire\n" +
            "expireAt\n" +
            "ttl\n" +
            "touch\n" +
            "touch\n" +
            "move\n" +
            "getSet\n" +
            "mget\n" +
            "setnx\n" +
            "setex\n" +
            "mset\n" +
            "msetnx\n" +
            "decrBy\n" +
            "decr\n" +
            "incrBy\n" +
            "incrByFloat\n" +
            "incr\n" +
            "append\n" +
            "substr\n" +
            "hset\n" +
            "hset\n" +
            "hget\n" +
            "hsetnx\n" +
            "hmset\n" +
            "hmget\n" +
            "hincrBy\n" +
            "hincrByFloat\n" +
            "hexists\n" +
            "hdel\n" +
            "hlen\n" +
            "hkeys\n" +
            "hvals\n" +
            "hgetAll\n" +
            "hrandfield\n" +
            "hrandfield\n" +
            "hrandfieldWithValues\n" +
            "rpush\n" +
            "lpush\n" +
            "llen\n" +
            "lrange\n" +
            "ltrim\n" +
            "lindex\n" +
            "lset\n" +
            "lrem\n" +
            "lpop\n" +
            "lpop\n" +
            "lpos\n" +
            "lpos\n" +
            "lpos\n" +
            "rpop\n" +
            "rpop\n" +
            "rpoplpush\n" +
            "sadd\n" +
            "smembers\n" +
            "srem\n" +
            "spop\n" +
            "spop\n" +
            "smove\n" +
            "scard\n" +
            "sismember\n" +
            "smismember\n" +
            "sinter\n" +
            "sinterstore\n" +
            "sunion\n" +
            "sunionstore\n" +
            "sdiff\n" +
            "sdiffstore\n" +
            "srandmember\n" +
            "srandmember\n" +
            "zadd\n" +
            "zadd\n" +
            "zadd\n" +
            "zadd\n" +
            "zaddIncr\n" +
            "zdiff\n" +
            "zdiffWithScores\n" +
            "zdiffStore\n" +
            "zrange\n" +
            "zrem\n" +
            "zincrby\n" +
            "zincrby\n" +
            "zrank\n" +
            "zrevrank\n" +
            "zrevrange\n" +
            "zrangeWithScores\n" +
            "zrevrangeWithScores\n" +
            "zrandmember\n" +
            "zrandmember\n" +
            "zrandmemberWithScores\n" +
            "zcard\n" +
            "zscore\n" +
            "zmscore\n" +
            "zpopmax\n" +
            "zpopmax\n" +
            "zpopmin\n" +
            "zpopmin\n" +
            "watch\n" +
            "sort\n" +
            "sort\n" +
            "sort\n" +
            "sort\n" +
            "lmove\n" +
            "blmove\n" +
            "blpop\n" +
            "blpop\n" +
            "brpop\n" +
            "brpop\n" +
            "getKeysAndTimeout\n" +
            "blpop\n" +
            "brpop\n" +
            "bzpopmax\n" +
            "bzpopmin\n" +
            "blpop\n" +
            "blpop\n" +
            "brpop\n" +
            "brpop\n" +
            "zcount\n" +
            "zcount\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScoreWithScores\n" +
            "zremrangeByRank\n" +
            "zremrangeByScore\n" +
            "zremrangeByScore\n" +
            "zunion\n" +
            "zunionWithScores\n" +
            "zunionstore\n" +
            "zunionstore\n" +
            "zinter\n" +
            "zinterWithScores\n" +
            "zinterstore\n" +
            "zinterstore\n" +
            "zlexcount\n" +
            "zrangeByLex\n" +
            "zrangeByLex\n" +
            "zrevrangeByLex\n" +
            "zrevrangeByLex\n" +
            "zremrangeByLex\n" +
            "strlen\n" +
            "lpushx\n" +
            "persist\n" +
            "rpushx\n" +
            "echo\n" +
            "linsert\n" +
            "brpoplpush\n" +
            "setbit\n" +
            "setbit\n" +
            "getbit\n" +
            "setrange\n" +
            "getrange\n" +
            "bitpos\n" +
            "bitpos\n" +
            "configGet\n" +
            "configSet\n" +
            "subscribe\n" +
            "publish\n" +
            "psubscribe\n" +
            "getParams\n" +
            "eval\n" +
            "eval\n" +
            "eval\n" +
            "evalsha\n" +
            "evalsha\n" +
            "evalsha\n" +
            "scriptExists\n" +
            "scriptExists\n" +
            "scriptLoad\n" +
            "slowlogGet\n" +
            "slowlogGet\n" +
            "objectRefcount\n" +
            "objectEncoding\n" +
            "objectIdletime\n" +
            "objectHelp\n" +
            "objectFreq\n" +
            "bitcount\n" +
            "bitcount\n" +
            "bitop\n" +
            "sentinelMasters\n" +
            "sentinelGetMasterAddrByName\n" +
            "sentinelReset\n" +
            "sentinelSlaves\n" +
            "sentinelFailover\n" +
            "sentinelMonitor\n" +
            "sentinelRemove\n" +
            "sentinelSet\n" +
            "dump\n" +
            "restore\n" +
            "restoreReplace\n" +
            "restore\n" +
            "pexpire\n" +
            "pexpireAt\n" +
            "pttl\n" +
            "psetex\n" +
            "clientKill\n" +
            "clientGetname\n" +
            "clientList\n" +
            "clientList\n" +
            "clientInfo\n" +
            "clientSetname\n" +
            "clientId\n" +
            "clientUnblock\n" +
            "migrate\n" +
            "migrate\n" +
            "scan\n" +
            "scan\n" +
            "hscan\n" +
            "sscan\n" +
            "zscan\n" +
            "clusterNodes\n" +
            "readonly\n" +
            "clusterMeet\n" +
            "clusterReset\n" +
            "clusterAddSlots\n" +
            "clusterDelSlots\n" +
            "clusterInfo\n" +
            "clusterGetKeysInSlot\n" +
            "clusterSetSlotNode\n" +
            "clusterSetSlotMigrating\n" +
            "clusterSetSlotImporting\n" +
            "clusterSetSlotStable\n" +
            "clusterForget\n" +
            "clusterFlushSlots\n" +
            "clusterKeySlot\n" +
            "clusterCountKeysInSlot\n" +
            "clusterSaveConfig\n" +
            "clusterReplicate\n" +
            "clusterSlaves\n" +
            "clusterFailover\n" +
            "clusterSlots\n" +
            "asking\n" +
            "pubsubChannels\n" +
            "pubsubNumPat\n" +
            "pubsubNumSub\n" +
            "close\n" +
            "setDataSource\n" +
            "pfadd\n" +
            "pfcount\n" +
            "pfcount\n" +
            "pfmerge\n" +
            "geoadd\n" +
            "geoadd\n" +
            "geoadd\n" +
            "geodist\n" +
            "geodist\n" +
            "geohash\n" +
            "geopos\n" +
            "georadius\n" +
            "georadiusReadonly\n" +
            "georadius\n" +
            "georadiusStore\n" +
            "georadiusReadonly\n" +
            "georadiusByMember\n" +
            "georadiusByMemberReadonly\n" +
            "georadiusByMember\n" +
            "georadiusByMemberStore\n" +
            "georadiusByMemberReadonly\n" +
            "moduleLoad\n" +
            "moduleUnload\n" +
            "moduleList\n" +
            "aclSetUser\n" +
            "aclSetUser\n" +
            "aclDelUser\n" +
            "aclGetUser\n" +
            "aclUsers\n" +
            "aclList\n" +
            "aclWhoAmI\n" +
            "aclCat\n" +
            "aclCat\n" +
            "aclLog\n" +
            "aclLog\n" +
            "aclLog\n" +
            "aclGenPass\n" +
            "aclLoad\n" +
            "aclSave\n" +
            "bitfield\n" +
            "bitfieldReadonly\n" +
            "hstrlen\n" +
            "memoryDoctor\n" +
            "memoryUsage\n" +
            "memoryUsage\n" +
            "xadd\n" +
            "xadd\n" +
            "xadd\n" +
            "xlen\n" +
            "xrange\n" +
            "xrange\n" +
            "xrevrange\n" +
            "xrevrange\n" +
            "xread\n" +
            "xread\n" +
            "xack\n" +
            "xgroupCreate\n" +
            "xgroupSetID\n" +
            "xgroupDestroy\n" +
            "xgroupDelConsumer\n" +
            "xdel\n" +
            "xtrim\n" +
            "xtrim\n" +
            "xreadGroup\n" +
            "xreadGroup\n" +
            "xpending\n" +
            "xpending\n" +
            "xpending\n" +
            "xclaim\n" +
            "xclaim\n" +
            "xclaimJustId\n" +
            "xautoclaim\n" +
            "xautoclaimJustId\n" +
            "xinfoStream\n" +
            "xinfoGroup\n" +
            "xinfoConsumers\n" +
            "sendCommand\n" +
            "sendBlockingCommand";
}
