package com.coral.kbs.tool.count;

/**
 * @author wuhao
 * @createTime 2021-05-18 12:07:00
 */
public class StrCountOld {
    public static final String str = "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "Jedis\n" +
            "ping\n" +
            "set\n" +
            "set\n" +
            "get\n" +
            "quit\n" +
            "exists\n" +
            "del\n" +
            "type\n" +
            "flushDB\n" +
            "keys\n" +
            "randomKey\n" +
            "rename\n" +
            "renamenx\n" +
            "expire\n" +
            "expireAt\n" +
            "ttl\n" +
            "select\n" +
            "move\n" +
            "flushAll\n" +
            "getSet\n" +
            "mget\n" +
            "setnx\n" +
            "setex\n" +
            "setnxex\n" +
            "mset\n" +
            "msetnx\n" +
            "decrBy\n" +
            "decr\n" +
            "incrBy\n" +
            "incrByEx\n" +
            "incr\n" +
            "append\n" +
            "substr\n" +
            "hset\n" +
            "hget\n" +
            "hsetnx\n" +
            "hmset\n" +
            "hmget\n" +
            "hincrBy\n" +
            "hexists\n" +
            "hdel\n" +
            "hlen\n" +
            "hkeys\n" +
            "hvals\n" +
            "hgetAll\n" +
            "rpush\n" +
            "lpush\n" +
            "llen\n" +
            "lrange\n" +
            "ltrim\n" +
            "lindex\n" +
            "lset\n" +
            "lrem\n" +
            "lpop\n" +
            "rpop\n" +
            "rpoplpush\n" +
            "sadd\n" +
            "smembers\n" +
            "srem\n" +
            "spop\n" +
            "smove\n" +
            "scard\n" +
            "sismember\n" +
            "sinter\n" +
            "sinterstore\n" +
            "sunion\n" +
            "sunionstore\n" +
            "sdiff\n" +
            "sdiffstore\n" +
            "srandmember\n" +
            "zadd\n" +
            "zadd\n" +
            "zrange\n" +
            "zrem\n" +
            "zincrby\n" +
            "zrank\n" +
            "zrevrank\n" +
            "zrevrange\n" +
            "zrangeWithScores\n" +
            "zrevrangeWithScores\n" +
            "zcard\n" +
            "zscore\n" +
            "watch\n" +
            "sort\n" +
            "sort\n" +
            "blpop\n" +
            "sort\n" +
            "sort\n" +
            "brpop\n" +
            "auth\n" +
            "subscribe\n" +
            "publish\n" +
            "psubscribe\n" +
            "zcount\n" +
            "zcount\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScore\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "zrangeByScoreWithScores\n" +
            "getTupledSet\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScoreWithScores\n" +
            "zrevrangeByScore\n" +
            "zrevrangeByScoreWithScores\n" +
            "zremrangeByRank\n" +
            "zremrangeByScore\n" +
            "zremrangeByScore\n" +
            "zunionstore\n" +
            "zunionstore\n" +
            "zinterstore\n" +
            "zinterstore\n" +
            "strlen\n" +
            "lpushx\n" +
            "persist\n" +
            "rpushx\n" +
            "echo\n" +
            "linsert\n" +
            "brpoplpush\n" +
            "setbit\n" +
            "getbit\n" +
            "setrange\n" +
            "getrange\n" +
            "configGet\n" +
            "configSet\n" +
            "eval\n" +
            "getParams\n" +
            "eval\n" +
            "eval\n" +
            "evalsha\n" +
            "getEvalResult\n" +
            "evalsha\n" +
            "evalsha\n" +
            "scriptExists\n" +
            "scriptExists\n" +
            "scriptLoad\n" +
            "slowlogGet\n" +
            "slowlogGet\n" +
            "objectRefcount\n" +
            "objectEncoding\n" +
            "objectIdletime\n" +
            "zclear\n" +
            "hclear\n" +
            "qclear\n" +
            "sscan\n" +
            "sscan\n" +
            "sscan\n" +
            "sscan\n" +
            "hscan\n" +
            "hscan\n" +
            "hscan\n" +
            "hscan";
}
